all: Hopkins_Brent_QuickSort.cpp Hopkins_Brent_InputFileGenerator.cpp
	g++ Hopkins_Brent_QuickSort.cpp -o Hopkins_Brent_QuickSort
	g++ Hopkins_Brent_InputFileGenerator.cpp -o Hopkins_Brent_InputFileGenerator



