
Hopkins_Brent_QuickSort: Hopkins_Brent_QuickSort.cpp
	g++ -o Hopkins_Brent_QuickSort


Hopkins_Brent_InputFileGenerator: Hopkins_Brent_InputFileGenerator.cpp
	g++ -o Hopkins_Brent_InputFileGenerator

